baseURL: "https://saurabh-khanna.github.io" 
title: Saurabh Khanna
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 10

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        - name: Teaching
          url: teaching/
          weight: 2
        - name: Code
          url: https://github.com/saurabh-khanna
          weight: 3
        - name: Invisible Information Lab
          url: https://theinvisiblelab.org/
          weight: 4

params:
    description: "This website hosts Saurabh Khanna's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Saurabh Khanna
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["teaching","publications","code"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Saurabh Khanna
          subtitle: "I am an Assistant Professor of Communication Science at the University of Amsterdam, and a Research Fellow at the University of Oxford. I lead research on the diversity and limits of human knowledge at the Invisible Information Lab. I received my PhD in Education Policy & Computer Science from Stanford University, where I was a Human-centered AI Fellow, a Data Science Scholar, and a William R and Sara Hart Kimball Fellow. My prior background spans Economics at Stanford, Computer Science at BITS Pilani, and Education at TISS."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications/
            - name: Teaching
              url: teaching/
            - name: Code
              url: https://github.com/saurabh-khanna
            - name: Invisible Information Lab
              url: https://theinvisiblelab.org/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:saurabh.khanna@uva.nl
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=if4Y2B0AAAAJ
        - name: GitHub
          url: https://github.com/saurabh-khanna
        - name: ORCID
          url: https://orcid.org/0000-0002-9346-4896
        - name: LinkedIn
          url: https://www.linkedin.com/in/saurabh90/
        - name: Office Hours
          url: https://outlook.office.com/bookwithme/user/4b902255be4b43aa96b3772ef17c15d3@uva.nl/meetingtype/RUUS252nbUSBC19Yq8fXyg2?anonymous&ismsaljsauthenabled&ep=mlink
        - name: Location
          url: location/

    assets:
        disableScrollBarStyle: true
        favicon: "favicon.svg"
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Saurabh Khanna"
      icon: favicon.svg
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
