baseURL: "https://saurabh-khanna.github.io" 
title: Saurabh Khanna
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Lab
          url: https://theinvisiblelab.org/
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Books
          url: books/
          weight: 3
        - name: Teaching
          url: courses/
          weight: 4
        - name: CV
          url: cv.pdf
          weight: 5

params:
    description: "This website hosts Saurabh Khanna's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Saurabh Khanna
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Saurabh Khanna
          subtitle: "I am an Assistant Professor of Communication Science at the University of Amsterdam, and a Research Fellow at the University of Oxford. I lead research on invisible information, studying the diversity and limits of human knowledge in an increasingly digitized world. <div style='margin-bottom: 0.5em;'></div> I received my PhD in Education Policy & Computer Science from Stanford University, where I was a Human-centered AI Fellow, a Data Science Scholar, and a William R and Sara Hart Kimball Fellow. My prior background spans Economics [Stanford], Computer Science Engineering [BITS Pilani], and Education [TISS]."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Lab
              url: https://theinvisiblelab.org/
            - name: Papers
              url: papers/
            - name: Books
              url: books/
            - name: Teaching
              url: courses/
            - name: CV
              url: cv.pdf

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:saurabh.khanna@uva.nl
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=if4Y2B0AAAAJ
        - name: GitHub
          url: https://github.com/saurabh-khanna
        - name: ORCID
          url: https://orcid.org/0000-0002-9346-4896
        - name: Stack Overflow
          url: https://stackoverflow.com/users/12385481

    assets:
        disableScrollBarStyle: true
        favicon: "favicon.svg"
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Saurabh Khanna"
      icon: favicon.svg
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
